### ISSUE TITLE
HIGH_PRIO: Unable to fetch *ANY* wine engine after staging x86 4.9 build

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#881] opened 2019-03-05 03:49 UTC
Results in: 

![image](https://user-images.githubusercontent.com/11302521/53779792-defab400-3f01-11e9-8f76-d4ee80993585.png)

HOTFIX: Install wine manually.

Suspect bug?

_Originally posted by @Kreyren in https://github.com/PhoenicisOrg/scripts/pull/797#issuecomment-469525958_

**Comment by plata** [comment] 2019-03-05 07:50
Any error during Wine installation? What exactly did you do?

**Comment by ImperatorS79** [comment] 2019-03-05 08:39
@Kreyren Are there files in `.Phoenicis/engines/wine/staging-linux-x86/4.2/bin` ?

**Comment by Zemogiter** [comment] 2019-03-05 09:09
This error mentions wine staging 4.2 x86 but there is no such wine in Engines tab.
```
java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/jonasz/.Phoenicis/engines//wine/staging-linux-x86/4.2/bin/wine" (in directory "/home/jonasz/.Phoenicis/containers/wineprefix/League of Legends"): error=2, Nie ma takiego pliku ani katalogu
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.JavaAdapterServices.wrapThrowable(JavaAdapterServices.java:285)
	at jdk.nashorn.javaadapters.org_phoenicis_engines_Engine.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$913$4947AAAZZA$\^eval\_.run(engines.wine.engine.object:178)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$912$219A$\^eval\_$cu1$restOf.regedit#open(engines.wine.plugins.regedit:12)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$899$287$\^eval\_$cu1$restOf.luna(engines.wine.verbs.luna:29)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$858$493$\^eval\_$cu1$restOf.go(engines.wine.quick_script.installer_script:72)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$826$603$\^eval\_.run(<eval>:18)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$825$\^eval\_$cu1$restOf.:program(<eval>:133)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/home/jonasz/.Phoenicis/engines//wine/staging-linux-x86/4.2/bin/wine" (in directory "/home/jonasz/.Phoenicis/containers/wineprefix/League of Legends"): error=2, Nie ma takiego pliku ani katalogu
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$964$7066AAAZZA$\^eval\_$cu1$restOf.run(engines.wine.engine.implementation:267)
	... 22 more
Caused by: java.io.IOException: error=2, Nie ma takiego pliku ani katalogu
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more
```

**Comment by Kreyren** [comment] 2019-03-07 22:20
> @Kreyren Are there files in `.Phoenicis/engines/wine/staging-linux-x86/4.2/bin` ?

can't check atm

**Comment by Kreyren** [comment] 2019-03-07 22:33
update: set version on 4.2 same issue, 4.1 is only present:

```
kreyren@debian:~$ ls .Phoenicis/engines/wine/staging-linux-amd64/
4.1
```

Phoenicis seems to trying to install 4.2:
```
ts from git-repository https://github.com/KREY-PhoenicisOrg/compatibilators.git, local folder: /home/kreyren/.Phoenicis/cache/git1877264162, branch: leagueoflegends
[INFO ] org.phoenicis.repository.types.GitRepository (l.76) - Begin fetching process of git-repository https://github.com/PhoenicisOrg/scripts.git, local folder: /home/kreyren/.Phoenicis/cache/git377944301, branch: master
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/kreyren/.Phoenicis/cache/git1877264162
[INFO ] org.phoenicis.repository.types.GitRepository (l.145) - Opening git-repository https://github.com/PhoenicisOrg/scripts.git, local folder: /home/kreyren/.Phoenicis/cache/git377944301, branch: master
[INFO ] org.phoenicis.repository.types.GitRepository (l.149) - Pulling new commits from git-repository https://github.com/PhoenicisOrg/scripts.git, local folder: /home/kreyren/.Phoenicis/cache/git377944301, branch: master
[INFO ] org.phoenicis.repository.types.LocalRepository (l.77) - Reading directory : /home/kreyren/.Phoenicis/cache/git377944301
Warning: Nashorn engine is planned to be removed from a future JDK release
[WARN ] org.phoenicis.javafx.views.mainwindow.installations.dto.InstallationDTO (l.56) - Installation ID (League of Legends_1551997877444) contains invalid characters, will remove them.
Installing version: 4.2
Installing version: 4.2

```

**Comment by plata** [comment] 2019-03-08 09:22
Does this issue only occur with certain Wine versions? E.g. does stable 4.0 install?

**Comment by Kreyren** [comment] 2019-03-08 10:54
@plata I understand that LATEST_STAGING is set on wine 4.2 that is not present in phoenicis based on entry from engines from GUI. Can you confirm? 

Didn't check 4.0

**Comment by madoar** [comment] 2019-03-08 11:00
It seems like winebuilt didn't build Wine 4.2 Staging for amd64 linux, see https://www.playonlinux.com/wine/binaries/phoenicis/staging-linux-amd64/

**Comment by plata** [comment] 2019-03-08 11:06
That should be an issue in winebuild then.

**Comment by Kreyren** [comment] 2019-03-08 20:27
@plata Move it in winebuild then, i wasn't aware what the issue was at the time of filing the bug.

**Comment by madoar** [comment] 2019-03-15 22:30
@Kreyren Wine 4.2 seems to be built now, can you try again?

**Comment by Kreyren** [comment] 2019-03-16 06:31
```javascript
.wineVersion(LATEST_STAGING_VERSION)
```` works fine

![image](https://user-images.githubusercontent.com/11302521/54471654-b3f34880-47bc-11e9-968c-7c048d06819e.png)

---

```javascript
.wineVersion("4.2")
```

Still results in err
![image](https://user-images.githubusercontent.com/11302521/54471685-282dec00-47bd-11e9-9ea4-1c4b7f05471c.png)

![image](https://user-images.githubusercontent.com/11302521/54471692-527fa980-47bd-11e9-87bf-ed3c578d2a28.png)

repos ware refreshed.

Also it works if installed in engines?
![image](https://user-images.githubusercontent.com/11302521/54471702-7347ff00-47bd-11e9-896b-17022afc74b6.png)

**Comment by Kreyren** [comment] 2019-05-20 00:19
Changed on blocker since this issue breaks engine.

**Comment by Kreyren** [comment] 2019-05-20 00:31
![image](https://user-images.githubusercontent.com/11302521/57990445-03007700-7aa7-11e9-8004-d5c9c83609f3.png)

Engines tab is not working resulting in hugeass output: https://gist.github.com/Kreyren/ff4726ca034ae2f30658ea8adaa15c4e

I believe that this is relevant to issue presented.

**Comment by Kreyren** [comment] 2019-05-20 00:32
Probably relevant https://github.com/PhoenicisOrg/phoenicis-winebuild/issues/79

**Comment by Kreyren** [comment] 2019-05-20 00:34
Maybe caused by https://github.com/PhoenicisOrg/wine-sources/issues/2 ?

**Comment by ImperatorS79** [comment] 2019-05-20 08:15
I think this is caused when variable describing latest available wine version inside this repo are updated before they are actually built on the web service.

**Comment by Kreyren** [comment] 2019-05-20 18:17
> I think this is caused when variable describing latest available wine version inside this repo are updated before they are actually built on the web service.

tried with wine 4.2 with same issue.

**Comment by ImperatorS79** [comment] 2019-06-05 11:10
@Kreyren Could you go in one of the container which has been created with that wine version, and try to launch an application through wine to see what happens (Container tab -> engine tools -> open a terminal). Then post the output.

**Comment by Kreyren** [comment] 2019-06-05 17:14
@ImperatorS79 I'm on debian now and i don't have this issue anymore, it might be something gentoo related.

EDIT: Using totally different system atm so it might be also hardware related

**Comment by ImperatorS79** [comment] 2019-06-05 17:15
I bet it was the runtime ^^. I will close this. Someone can open a new issue if he encounters this again.

**Comment by Kreyren** [comment] 2019-06-05 17:24
> I will close this. Someone can open a new issue if he encounters this again.

Agreed

**Comment by Kreyren** [comment] 2019-06-05 17:53
Spoke too soon 
![image](https://user-images.githubusercontent.com/11302521/58978063-abddf000-8790-11e9-967e-f1c0ff9bb430.png)

@ImperatorS79 reopen

Seems to be issue with steam scripts installers.

**Comment by ImperatorS79** [comment] 2019-06-05 17:59
Ok, interesting

**Comment by Kreyren** [comment] 2019-06-05 18:03
> Ok, interesting
> @Kreyren could you copy paste the log instead of an image ?

```
java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/kreyren/.Phoenicis/engines//wine/staging-linux-x86/4.9/bin/wine" (in directory "/home/kreyren/.Phoenicis/containers/wineprefix/Minion Masters"): error=2, No such file or directory
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.JavaAdapterServices.wrapThrowable(JavaAdapterServices.java:285)
	at jdk.nashorn.javaadapters.org_phoenicis_engines_Engine.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$494$4949AAAZZA$\^eval\_.run(engines.wine.engine.object:178)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$493$219A$\^eval\_$cu1$restOf.regedit#open(engines.wine.plugins.regedit:12)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$479$287$\^eval\_$cu1$restOf.luna(engines.wine.verbs.luna:29)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$414$5474$\^eval\_$cu1$restOf.go(engines.wine.quick_script.steam_script:116)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$389$300$\^eval\_.run(<eval>:11)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$388$\^eval\_$cu1$restOf.:program(<eval>:29)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/home/kreyren/.Phoenicis/engines//wine/staging-linux-x86/4.9/bin/wine" (in directory "/home/kreyren/.Phoenicis/containers/wineprefix/Minion Masters"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$546$11334AAAZZA$\^eval\_$cu1$restOf.run(engines.wine.engine.implementation:380)
	... 22 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more
```

Aldo mafia II is working :thinking: maybe my configuration? I have git cloned my compatibilators repo that is synced with master and using repository to read from local file only?

**Comment by ImperatorS79** [comment] 2019-06-05 18:37
@qparis Can you launch the build of that version ?

**Comment by qparis** [comment] 2019-06-05 18:41
@ImperatorS79 Staging linux amd64 4.9, right?

**Comment by Kreyren** [comment] 2019-06-05 18:42
@qparis x86 4.9

**Comment by Kreyren** [comment] 2019-06-05 18:46
Or hotfix it by removing staging 4.9 x86 from `LATEST_STAGING_VERSION` when it's not built yet.. should be sanitized..

**Comment by qparis** [comment] 2019-06-05 18:46
https://www.playonlinux.com/wine/

**Comment by ImperatorS79** [comment] 2019-06-05 18:50
There is an issue on the phoenicis-winebuild, so that the value of LATEST_STAGING_VERSION would be provided by playonlinux.com

**Comment by Kreyren** [comment] 2019-06-05 18:52
@ImperatorS79 reference it

**Comment by Kreyren** [comment] 2019-06-05 19:12
engine is built, but i'm still getting same error.

**Comment by ImperatorS79** [comment] 2019-06-05 19:14
@qparis Did you update the environment because in the logs it still says that Mingw is missing.
Also the build was too fast... There seems to be a problem.

**Comment by Kreyren** [comment] 2019-06-05 19:15
~~called it~~

**Comment by Kreyren** [comment] 2019-06-05 19:15
nwm it's downloading now 
![image](https://user-images.githubusercontent.com/11302521/58983432-66272480-879c-11e9-835b-5172c9971794.png)

**Comment by qparis** [comment] 2019-06-05 19:39
> @qparis Did you update the environment because in the logs it still says that Mingw is missing.
> Also the build was too fast... There seems to be a problem.

I have. But be careful, the logs are concatenated. 
The build was fast but it ran correctly

**Comment by Kreyren** [comment] 2019-06-05 19:40
Noticed new build finished.. now it fails with
```
javax.script.ScriptException: SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found eof

^ in engines.wine.engine.implementation at line number 124
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:461)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: engines.wine.engine.implementation:124 SyntaxError: Invalid JSON: <json>:1:0 Expected json literal but found eof

^
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:160)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.syntaxError(ECMAErrors.java:145)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:81)
	at jdk.scripting.nashorn/jdk.nashorn.internal.objects.NativeJSON.parse(NativeJSON.java:118)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1503$4170A$\^eval\_$cu1$restOf._installRuntime(engines.wine.engine.implementation:124)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1498$1596AA$\^eval\_$cu1$restOf.install(engines.wine.engine.implementation:36)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1496$11334AAAZZA$\^eval\_$cu1$restOf.run(engines.wine.engine.implementation:297)
	at jdk.nashorn.javaadapters.org_phoenicis_engines_Engine.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1488$4949AAAZZA$\^eval\_.run(engines.wine.engine.object:178)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1487$219A$\^eval\_$cu1$restOf.regedit#open(engines.wine.plugins.regedit:12)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1473$287$\^eval\_$cu1$restOf.luna(engines.wine.verbs.luna:29)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1440$493$\^eval\_$cu1$restOf.go(engines.wine.quick_script.installer_script:72)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1376$340$\^eval\_.run(<eval>:11)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$1375$\^eval\_$cu1$restOf.:program(<eval>:34)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	... 10 more
Caused by: jdk.nashorn.internal.runtime.ParserException: <json>:1:0 Expected json literal but found eof

^
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:529)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.error(JSONParser.java:533)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.expectedError(JSONParser.java:541)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parseLiteral(JSONParser.java:161)
	at jdk.scripting.nashorn/jdk.nashorn.internal.parser.JSONParser.parse(JSONParser.java:148)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.JSONFunctions.parse(JSONFunctions.java:79)
	... 26 more
```

EDIT: Grabbing the commit w8

EDIT2: Same error after grabbing the commit.

**Comment by Kreyren** [comment] 2019-06-05 19:40
@qparis 
> The build was fast but it ran correctly

Full doubt

**Comment by qparis** [comment] 2019-06-05 19:53
> @qparis
> 
> > The build was fast but it ran correctly
> 
> Full doubt

Any proof? As far as I am concerned I'm confident that the build ran.

https://www.playonlinux.com/wine/binaries/phoenicis/staging-linux-x86/PlayOnLinux-wine-4.9-staging-linux-x86.tar.gz
https://www.playonlinux.com/wine/logs/staging-linux-x86/PlayOnLinux-wine-4.9-staging-linux-x86.log

**Comment by Kreyren** [comment] 2019-06-05 19:55
> > @qparis
> > > The build was fast but it ran correctly
> > 
> > 
> > Full doubt
> 
> Any proof? As far as I am concerned I'm confident that the build ran.
> 
> https://www.playonlinux.com/wine/binaries/phoenicis/staging-linux-x86/PlayOnLinux-wine-4.9-staging-linux-x86.tar.gz
> https://www.playonlinux.com/wine/logs/staging-linux-x86/PlayOnLinux-wine-4.9-staging-linux-x86.log

https://github.com/PhoenicisOrg/scripts/issues/881#issuecomment-499226210

**Comment by qparis** [comment] 2019-06-05 20:29
> > > @qparis
> > > > The build was fast but it ran correctly
> > > 
> > > 
> > > Full doubt
> > 
> > 
> > Any proof? As far as I am concerned I'm confident that the build ran.
> > https://www.playonlinux.com/wine/binaries/phoenicis/staging-linux-x86/PlayOnLinux-wine-4.9-staging-linux-x86.tar.gz
> > https://www.playonlinux.com/wine/logs/staging-linux-x86/PlayOnLinux-wine-4.9-staging-linux-x86.log
> 
> --> [#881 (comment)](https://github.com/PhoenicisOrg/scripts/issues/881#issuecomment-499226210) <--

This is absolutely not a proof that the build did not run. This is a proof that phoenicis, in your case cannot build it.

Please don't rename issues, we are now losing track. 

I cannot reproduce the winebuild problem, so I will have to close the issue. Pleaase reopen an issue with more details and a clear explanation if the problem is proven

**Closed by qparis** 2019-06-05 20:29 UTC
Labels: bug

**Comment by Kreyren** [comment] 2019-06-05 20:32
@qparis provide info to diagnose it then.

**Comment by qparis** [comment] 2019-06-05 20:40
Reinstalle Phoenicis, rename your .phoenicis directory and retry

**Comment by Kreyren** [comment] 2019-06-05 20:51
@qparis works now, thanks <3

**Comment by Kreyren** [comment] 2019-06-06 23:44
I have this issue again, this time i nuked `~/.Phoenicis` and re-fetched git of phoenicis which result in: for any engine..

```
java.lang.RuntimeException: java.io.IOException: Cannot run program "/home/kreyren/.Phoenicis/engines//wine/staging-linux-x86/4.9/bin/wine" (in directory "/home/kreyren/.Phoenicis/containers/wineprefix/Magic The Gathering Arena"): error=2, No such file or directory
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.linker.JavaAdapterServices.wrapThrowable(JavaAdapterServices.java:285)
	at jdk.nashorn.javaadapters.org_phoenicis_engines_Engine.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$502$4949AAAZZA$\^eval\_.run(engines.wine.engine.object:178)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$501$219A$\^eval\_$cu1$restOf.regedit#open(engines.wine.plugins.regedit:12)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$487$287$\^eval\_$cu1$restOf.luna(engines.wine.verbs.luna:29)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$444$493$\^eval\_$cu1$restOf.go(engines.wine.quick_script.installer_script:72)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$391$372$\^eval\_.run(<eval>:12)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$390$\^eval\_$cu1$restOf.:program(<eval>:32)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Cannot run program "/home/kreyren/.Phoenicis/engines//wine/staging-linux-x86/4.9/bin/wine" (in directory "/home/kreyren/.Phoenicis/containers/wineprefix/Magic The Gathering Arena"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$542$11334AAAZZA$\^eval\_$cu1$restOf.run(engines.wine.engine.implementation:380)
	... 22 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 24 more
```

@qparis any idea why is this happening? it's very common on my system and super annoying..

**Comment by Kreyren** [comment] 2019-06-07 11:42
@plata / @ImperatorS79 re-open and move in winebuild plz

**Comment by ImperatorS79** [comment] 2019-06-07 15:19
1) Does the file exists ?
2) Try to execute it with output log (container tab->engine tools->terminal)

**Comment by plata** [comment] 2019-06-07 15:22
@Kreyren as it was working before and nothing changed in Phoenicis, I'm assuming that this is related to your setup rather than anything else.

**Comment by Kreyren** [comment] 2019-06-08 14:38
> Does the file exists ?

It does

> Try to execute it with output log (container tab->engine tools->terminal)

Can't reproduce atm, reproducable on random.

> I'm assuming that this is related to your setup rather than anything else.

Using standart debian buster setup and phoenicis was re-cloned from git..
