### ISSUE TITLE
Abstract: Remove wineprefix on fatal

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#822] opened 2019-01-15 14:52 UTC
Recommends removing created wineprefix if installer fails -> prevent possible issues.

**Comment by plata** [comment] 2019-01-15 16:23
This might have very weird side effects. For example, two scripts could use the same prefix. If the first is installed correctly and the second one fails, it would delete a working prefix.

**Comment by madoar** [comment] 2019-01-15 17:31
Another reason not to delete containers after a script error is, that it is often only possible to identify why a script failed by looking what the container contains.

**Comment by plata** [comment] 2019-01-15 17:40
Maybe what we could do: Show a wizard step if the prefix "xyz" shall be deleted.

**Comment by qparis** [comment] 2019-01-15 17:50
This is the way it is done (and it should be done imho) in POLv4: 
![image](https://user-images.githubusercontent.com/373645/51199203-79714a80-18f6-11e9-803a-477858d370ef.png)

**Comment by madoar** [comment] 2019-01-16 18:47
I'm not sure whether such a window can be shown with the current script installation process.
The issue is that in case a problem (error) occurs the whole installation process terminates and a popup dialog is shown, containing the error message.
This means that the installation wizard closes in case an error occurs without giving the user a chance to do any cleanup work.

I think we would need to change the way script installation errors are processed to support such a selection like @qparis suggests.

**Comment by qparis** [comment] 2019-01-16 19:32
I suggest showing this window on prefix creation, not when the script has failed

**Comment by madoar** [comment] 2019-01-16 19:35
@qparis for me that means the same thing, i.e. prefix creation is basically a part of the script execution. (at least this is how the user perceives it)

**Comment by qparis** [comment] 2019-01-16 19:38
Yep but if we manage the problem like this, there is no need to catch the error

**Comment by madoar** [comment] 2019-01-16 19:40
Yes, but it doesn't change the fact the we would need to change the installation process (i.e. the way script installation errors are processed).

**Comment by qparis** [comment] 2019-01-16 19:48
Why?

**Comment by madoar** [comment] 2019-01-16 19:53
Because by showing the error dialog popup, the whole installation process is simply terminated.
Thereby leaving no option to ask the user whether he wants to perform any cleanup measure (e.g. delete the container).

When taking a look at the previous posts again, I think we're talking about two different issues.

I'm talking about the case the installation script fails via a thrown exception. In this case the whole installation process is simply terminated, like mentioned above.

I think you're suggesting a check during the container creation, which checks that a container with the same name doesn't exist yet. This check doesn't lead to a thrown exception in case the container already exists.

**Comment by qparis** [comment] 2019-01-16 19:59
> I think you're suggesting a check during the container creation, which checks that a container with the same name doesn't exist yet. This check doesn't lead to a thrown exception in case the container already exists.

This is what I am suggesting yes. If we implement that, this issue is no longer required or at least less a priority

**Comment by madoar** [comment] 2019-01-16 20:04
Let's move your suggestion to add an addition "container already exists" check to a new issue.

I still think, that we need to ask the user, whether he wants to delete the container in case the script fails with error. This ensures, that a failed installation process is completely cleaned up.

**Comment by qparis** [comment] 2019-01-16 20:16
I don't think so. We need to analyse the average behavior. 

I tend to think that when a user encounter an error, he/she might click on Yes button under pressure, whatever is written. 
I think it is not the right moment to trigger irreversible actions

**Comment by Kreyren** [comment] 2019-01-16 20:16
i'm for POL4 implementation too.. We should display it if the wineprefix already exists.

**Comment by madoar** [comment] 2019-01-16 20:19
@Kreyren this is not about the POL4 implementation.

@qparis my issue is, why does a user require a possible broker container?
A script should throw an error if it is broken. In such a case I would expect Phoenicis to ask me whether I want to delete the broken container and start anew.

**Comment by qparis** [comment] 2019-01-16 20:19
For example imagine that you have a game installed and you want to install an extension, or a verb and it fails

**Comment by madoar** [comment] 2019-01-16 20:22
I know that there are cases where it is undesired to delete the container (for example if the shortcut couldn't be created for some reason but the game was downloaded and installed successfully).
But how often do these cases occur? In my opinion the most common script failure cause is a syntax error, which often leads to a broken (as in unusable) container.

**Comment by qparis** [comment] 2019-01-16 20:23
It won't happen often sure. But I don't think we are willing to take the responsibility of losing user data, if it is one case over 100000

**Comment by qparis** [comment] 2019-01-16 21:13
What about using something like git to manage the snapshot of a wineprefix?

**Comment by madoar** [comment] 2019-01-16 21:20
Isn't using git overkill? I mean I know of only three "states" which a container could consist of:
- the initial state (before the script has been executed)
- a failure state (the script has failed for some reason)
- a success state (the script has safely and successfully terminated)

Do we require a solution like git to realize these three steps?

**Comment by qparis** [comment] 2019-01-16 21:36
We could restore a prefix at any past state. (Uninstall a verb for example)

**Comment by madoar** [comment] 2019-01-16 21:40
That sounds like an interesting idea.
Should we only persist the state after installing a verb or executing an installation script or also inbetween? (i.e. after every command that has been executed inside a script?)

**Comment by qparis** [comment] 2019-01-16 21:42
Hum maybe we would have a commit() command, and open it to the scripters. Then we could decide to automatically use it in import steps: prefix creation, reg importation, when wine is terminated, etc...

**Comment by plata** [comment] 2019-01-17 18:08
For me these are different topics:
- check if container exists before creating it
- avoid dangling containers (topic of this issue)
- time machine functionality
We should handle them separately.

If you open separate issues, I will leave my comments there.

**Comment by plata** [comment] 2019-01-19 11:12
Closing because topic is tracked by the issues above.

**Closed by plata** 2019-01-19 11:12 UTC

**Comment by Kreyren** [comment] 2019-01-19 13:13
I'm abadoning the issue since it's outside of my qualification.
