### ISSUE TITLE
Add date of last update to the scripts

### ISSUE THREAD

**Issue by madoar** [PhoenicisOrg/scripts#188] opened 2017-03-07 21:37 UTC
I'm currently installing the updated League of Legends Beta Client script. 
What I'm missing in POL 5 is an indication of the "newness" of the script, i.e. when was the script last modified.
I think it would be useful to add a property to the scripts containing their last update, what do you think about this?

**Comment by feanor12** [comment] 2017-03-08 09:28
Sounds like a good idea. Maybe we should add a version number.

**Comment by plata** [comment] 2017-03-08 11:42
Good idea. However, I would get the change date automatically according to the git commit.

Adding an "improve this installer" should be quite easy. I would suggest to add this to the [description](https://github.com/PlayOnLinux/POL-POM-5/blob/master/phoenicis-javafx/src/main/java/org/phoenicis/javafx/views/mainwindow/apps/AppPanel.java). If we add the category name as parameter, we can build the GitHub link as:
```Java
"https://github.com/PlayOnLinux/Scripts/tree/master/" + category + "/" + application.getName()
```

**Comment by plata** [comment] 2017-03-08 12:13
There's a problem with all this: We cannot be sure about the source of the script. It could come from a LocalApplicationsSource. In this case, it wouldn't make any sense to link to GitHub.

This problem also affects the change date for the scripts. Maybe we cannot avoid adding the date manually.

**Comment by madoar** [comment] 2017-03-11 10:53
Can't we use the last modification date of the file if the script comes from a LocalApplicationsSource?

**Comment by plata** [comment] 2017-03-11 13:44
Maybe. But then there is ClasspathApplicationsSource and maybe WebApplicationsSource in the future. In the end you cannot compare anything. You might get the very same script from a LocalApplicationsSource and a GitApplicationsSource with different versions (even though the content is the same).

**Comment by plata** [comment] 2019-01-12 16:14
@madoar @qparis we should decide if we want to do this or not.

Currently I don't see a possible way how it could be done. Any versioning (except checksum) is invalid by design because there is no single source for a script (so it can very well happen that v4 from one repository is older than v3 from another). Therefore, the whole purpose of versioning cannot be achieved. I would suggest not to implement this and close the issue.

**Closed** 2019-03-03 10:27 UTC
