### ISSUE TITLE
League Of Legends - Wrong URL

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#777] opened 2019-01-02 20:07 UTC
https://riotgamespatcher-a.akamaihd.net/ShellInstaller/EUNE/LeagueofLegends_EUNE_Installer_2016_11_10.exe from https://github.com/PhoenicisOrg/scripts/edit/master/Applications/Games/League%20of%20Legends/Online/script.js

Results in 
![image](https://user-images.githubusercontent.com/11302521/50610187-f1d51600-0ec9-11e9-87c2-a36cb0880175.png)

Relevant(?): https://github.com/GloriousEggroll/leagueoflegends-linux

Relevant: https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe

Relevant: https://pastebin.com/MnkMRBBu

Conclusion: Unable to find more info on ShellInstaller

Using https://riotgamespatcher-a.akamaihd.net/releases/live/installer/deploy/League%20of%20Legends%20installer%20NA.exe

**Comment by Kreyren** [comment] 2019-01-03 04:03
Closed by https://github.com/PhoenicisOrg/scripts/pull/778#pullrequestreview-188855265

**Comment by plata** [comment] 2019-01-03 10:23
Just a hint: Instead of closing the issue manually, it's preferable to use https://help.github.com/articles/closing-issues-using-keywords/.

**Comment by Kreyren** [comment] 2019-01-03 18:53
@plata Noted

**Comment by Kreyren** [comment] 2019-01-03 18:53
fixes https://github.com/PhoenicisOrg/scripts/pull/778#pullrequestreview-188855265

**Comment by Kreyren** [comment] 2019-01-03 18:54
Fixes https://github.com/PhoenicisOrg/scripts/pull/778#pullrequestreview-188855265

**Closed** 2019-01-03 18:55 UTC

**Comment by mic-rigaud** [comment] 2019-10-20 12:59
I have the same problem on the flatpak version:

`
org.phoenicis.tools.http.DownloadException: Download of https://riotgamespatcher-a.akamaihd.net/ShellInstaller/EUW/LeagueofLegends_EUW_Installer_2016_11_10.exe has failed
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:241)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.get(Downloader.java:196)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.get(Downloader.java:93)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.get(Downloader.java:74)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$498$2585$\^eval\_$cu1$restOf.get([utils, functions, net, download]:124)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$487$1783$\^eval\_$cu1$restOf.get([utils, functions, net, resource]:101)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$470$827A$\^eval\_$cu1$restOf.run#L:22(<eval>:94)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$459$553$\^eval\_$cu1$restOf.go([engines, wine, quick_script, installer_script]:30)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$436$562$\^eval\_.run(<eval>:17)
	at jdk.nashorn.javaadapters.org_phoenicis_scripts_Installer.run(Unknown Source)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$435$\^eval\_$cu1$restOf.:program(<eval>:124)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:655)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:456)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:413)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:409)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:162)
	at java.scripting/javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornEngine.eval(NashornEngine.java:50)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.nashorn.NashornScriptInterpreter.runScript(NashornScriptInterpreter.java:35)
	at phoenicis.scripts@5.0-alpha-2/org.phoenicis.scripts.interpreter.BackgroundScriptInterpreter.lambda$runScript$0(BackgroundScriptInterpreter.java:35)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://riotgamespatcher-a.akamaihd.net/ShellInstaller/EUW/LeagueofLegends_EUW_Installer_2016_11_10.exe
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1913)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at phoenicis.tools@5.0-alpha-2/org.phoenicis.tools.http.Downloader.saveConnectionToStream(Downloader.java:214)
	... 24 more
`

**Comment by plata** [comment] 2019-10-21 16:51
@mic-rigaud the flatpak will use the released version of scripts until a new flatpak is released. If you need a newer version earlier, you can build a flatpak based on recent master yourself.
