### ISSUE TITLE
League of Legends link dead

### ISSUE THREAD

**Issue by rowbawts** [PhoenicisOrg/scripts#870] opened 2019-02-25 07:55 UTC
When you try to install the League script fails on the initial download of the installer because the link is old see [here](https://riotgamespatcher-a.akamaihd.net/ShellInstaller/NA/LeagueofLegends_NA_Installer_2016_05_13.exe)

**Comment by plata** [comment] 2019-02-26 16:20
Do you know what the link should be?

**Comment by madoar** [comment] 2019-02-26 16:41
This issues is likely linked to #797.

**Comment by rowbawts** [comment] 2019-03-01 04:01
Seems like it, but the links in the PR also have the same error.

**Comment by Kreyren** [comment] 2019-03-02 17:09
League Of Legends in not working in Phoenicis atm due https://github.com/PhoenicisOrg/scripts/issues/841

Once that is fixed we can make a merge request, working on DXVK support atm.

**Comment by Kreyren** [comment] 2019-03-02 17:12
Is noted, recommends closing the issue.

**Comment by Kreyren** [comment] 2019-03-08 21:25
Duplicate of https://github.com/PhoenicisOrg/scripts/issues/777

**Comment by plata** [comment] 2019-06-04 18:47
To be tracked in #797.

**Closed by plata** 2019-06-04 18:47 UTC
