### ISSUE TITLE
Run Wine app with custom environment variables

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#869] opened 2019-02-22 12:05 UTC
How do i make script to invoke `DXVK_CACHE=PATH wine` in phoenicis?

Reference: https://github.com/PhoenicisOrg/scripts/pull/795#partial-pull-merging

**Comment by ImperatorS79** [comment] 2019-02-22 15:05
Duplicate of #213.

**Comment by plata** [comment] 2019-02-23 12:26
This must be added as a new parameter for `engine#run()`, see: https://github.com/PhoenicisOrg/scripts/blob/a6bbe8d1d65278995dcf483ec8a33e7ab3127785/Engines/Wine/Engine/Implementation/script.js#L236

**Comment by Kreyren** [comment] 2019-02-23 20:51
:thinking: 

if already present example usage?

**Comment by plata** [comment] 2019-02-24 10:48
Just check where `Wine.run` is called.

**Closed** 2019-06-28 19:34 UTC
Labels: feature-request
