### ISSUE TITLE
QA: output progress for engines

### ISSUE THREAD

**Issue by Kreyren** [PhoenicisOrg/scripts#904] opened 2019-04-03 13:23 UTC
Downloading an engines sometimes takes time and phoenicis hangs on downloading message for +- 4 minutes untill it downloads an engine -> Recommends adding progress bar.

## Steps to reproduce
- Install any wine that is not present in phoenicis already.

Disclaimer can't make screenshot atm

**Comment by plata** [comment] 2019-04-03 15:59
@qparis assumes that this is an issue with a thread pool (i.e. no thread available to do the download).

duplicate of https://github.com/PhoenicisOrg/phoenicis/issues/1807

**Closed by plata** 2019-04-03 15:59 UTC
Labels: duplicate

**Comment by Kreyren** [comment] 2019-04-04 04:14
Just to verify:
![image](https://user-images.githubusercontent.com/11302521/55529264-69b50700-5698-11e9-86d1-94d5fa015c9d.png)

Meaning that no progress bar is rendered and phoenicis hangs for +- minutes if new engine is not present on the system, assuming that it's downloading?

 
![image](https://user-images.githubusercontent.com/11302521/55529289-8b15f300-5698-11e9-8609-16e9c9b5c07e.png)
![image](https://user-images.githubusercontent.com/11302521/55529293-91a46a80-5698-11e9-8994-7abb362b6907.png)

**Comment by plata** [comment] 2019-04-04 16:56
Yes, that's the known behavior.
